CC=$DIDBS_CC
CFLAGS="$DIDBS_ARCH_CFLAGS -Wall"
LDFLAGS="$DIDBS_ARCH_LDFLAGS"
export CC CFLAGS LDFLAGS

#PATH=$INSTALLDIR/bin:$EXTRAARGS/bin:$PATH
#export CC CFLAGS LDFLAGS BIGFILES PATH
#LD_LIBRARY_PATH="$INSTALLDIR/lib:$LD_LIBRARY_PATH"
#PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig:$PKG_CONFIG_PATH"
#export LD_LIBRARY_PATH PKG_CONFIG_PATH

#echo "env is:"
#env
#exit 1
